### ISSUE TITLE
Wordlist is extremely large

### ISSUE THREAD

**Issue by jseakle** [muffinista/botgle#1]
Hi!

I'm @jseakle on twitter, and I've been playing botgle quite a bit, fairly seriously. I feel like its popularity and fun is being held back a bit by the extreme size of the wordlist, which highly encourages typing in likely-sounding nonsense as fast as you can over actually looking for words you know. I feel kind of bad about doing it, but ten minutes is a long time, and it's just bad strategy to not utilize any downtime typing in everything even remotely reasonable. In [the most recent game I won](https://twitter.com/Botgle/status/694900332787286016), 5 out of 30 of my points were earned this way, nearly enough to cost me the game. And on top of that, the best words found by the stats bot includes "BURUT", which does not seem (from a bit of googling) to be an even remotely real English word! I've also noticed that any given name I've tried has been accepted - a lot of those are also words, but I kind of suspect a lot of proper nouns and names are incorrectly accepted as well.

It looks like from your commit message that your dictionary is a superset of SOWPODS - might I recommend restricting to to just SOWPODS, or maybe even something smaller? (SOWPODS does not contain BURUT, at least, but it's still enormous, and full of archaicisms (like COURB, also from that last game). The game would be perfectly fine with a dictionary half the size.)

Thanks for making botgle! It's lots of fun.

**Comment by muffinista** [comment]
Hi, thanks for the feedback! I agree that there are a lot of questionable words in the database. Weirdly, I think some of these words come from the original source of words I used, which is the default words file from Linux. BURUT is there, and it looks like the mistake I made is including proper nouns from that file.

I'm definitely happy to remove proper nouns from the game, which is about 25000 words, and I will think for a bit about just switching entirely to SOWPODS. I agree it probably wouldn't hurt the game at all.

**Comment by jseakle** [comment]
Yay, thanks!

Now that I've got my foot in the door, here's my much more controversial opinion: Boggle is a way better game when three-letter words are disallowed.

Of course, actually deviating from the printed rules has a lot of issues, and I understand completely if you are very reluctant to do it. But at the same time, you can do whatever you want, and it's just SO much more fun! Even when "type everything pronounceable" is less of a good strategy, many boards still just devolve into typing huge lists of rhyming three-letter words really fast. I personally prefer the minimum to be 5, so that one's entire time is spent looking for things that actually feel like you found them, rather than just looking at them, but that's pretty niche and would alienate less experienced players - I think 4 is really the sweet spot.

One thing you could do is add a fifth timeslot, not affecting the regular schedule, where you try this and other new ideas and solicit feedback.

Or you could ignore my silly ideas and carry on with the excellent program you've written as is :)

**Comment by muffinista** [comment]
Hey, so I switched to just sowpods for now, and it seems good. I'm probably not going to block 3-letter words for now, although I will keep it in mind. Thanks!
